### ISSUE TITLE
树图示例所有文字都显示在最上面了

### ISSUE THREAD

**Issue by kxr224** [WsmDyj/echarts-for-taro#22]
树图示例中，文字显示有bug。
![微信图片_20191115170101](https://user-images.githubusercontent.com/28681083/68930522-89351600-07c9-11ea-90b0-5420c334f93d.jpg)

**Comment by kxr224** [comment]
解决了...

**Comment by fancyfff** [comment]
> 解决了...

请问是如何解决的？ 折线图也遇到了类似的问题
